trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Nightly build
  branches:
    include:
    - main
  always: true

variables:
  - group: ChokuretsuSecrets
  - name: PatchVersion
    value: v0.1.$(Build.BuildNumber)

resources:
  repositories:
  - repository: ChokuretsuTranslationStrings
    type: github
    endpoint: haroohie-club
    name: haroohie-club/ChokuretsuTranslationStrings
  - repository: ChokuretsuTranslationAssets
    type: github
    endpoint: haroohie-club
    name: haroohie-club/ChokuretsuTranslationAssets
  - repository: ChokuretsuTranslationUtility
    type: github
    endpoint: haroohie-club
    name: haroohie-club/ChokuretsuTranslationUtility

jobs:
- job:
  displayName: Build & Publish
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
  - checkout: ChokuretsuTranslationStrings
  - checkout: ChokuretsuTranslationAssets
  - checkout: ChokuretsuTranslationUtility
  - powershell: |
      Write-Host "Downloading devkitARM..."
      Invoke-WebRequest -Uri https://dockerbootstrap.blob.core.windows.net/chokuretsu/devkitPro.zip?$($env:SAS) -OutFile devkitPro.zip
      Write-Host "Downloading NitroPacker..."
      Invoke-WebRequest -Uri https://dockerbootstrap.blob.core.windows.net/chokuretsu/NitroPacker.zip?$($env:SAS) -OutFile NitroPacker.zip
      Write-Host "Downloading ROM..."
      Invoke-WebRequest -Uri https://dockerbootstrap.blob.core.windows.net/chokuretsu/original.zip?$($env:SAS) -OutFile original.zip
      Write-Host "Downloading xdelta3..."
      Invoke-WebRequest -Uri https://dockerbootstrap.blob.core.windows.net/chokuretsu/xdelta3.zip?$($env:SAS) -OutFile xdelta3.zip
      
      Write-Host "Unzipping devkitARM..."
      Expand-Archive devkitPro.zip
      Write-Host "Unzipping NitroPacker..."
      Expand-Archive NitroPacker.zip
      Write-Host "Unzipping ROM..."
      Expand-Archive original.zip
      Write-Host "Unzipping xdelta3..."
      Expand-Archive xdelta3.zip
      
      Write-Host "Moving ROM to ChokuretsuTranslationBuild..."
      Move-Item -Path original/original.nds -Destination ChokuretsuTranslationBuild\original.nds

    env:
      SAS: $(ChokuretsuSAS)
    displayName: Download dependencies
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: ChokuretsuTranslationUtility/HaruhiChokuretsuCLI/HaruhiChokuretsuCLI.csproj
    displayName: Build HaruhiChokuretsuCLI
  - task: PowerShell@2
    inputs:
      filePath: ChokuretsuTranslationBuild/setup.ps1
      arguments: -nitroPacker "$(Build.SourcesDirectory)/NitroPacker/NitroPacker.exe"
      workingDirectory: $(Build.SourcesDirectory)/ChokuretsuTranslationBuild
    displayName: Run setup
  - task: PowerShell@2
    inputs:
      filePath: ChokuretsuTranslationBuild/build_arc.ps1
      arguments: -haruhiCli "$(Build.SourcesDirectory)/ChokuretsuTranslationUtility/HaruhiChokuretsuCLI/bin/Debug/net6.0/HaruhiChokuretsuCLI.exe" -stringsFolder "$(Build.SourcesDirectory)/ChokuretsuTranslationStrings" -assetsFolder "$(Build.SourcesDirectory)/ChokuretsuTranslationAssets" -resxLangCode "en" -version "$(PatchVersion)"
      workingDirectory: $(Build.SourcesDirectory)/ChokuretsuTranslationBuild
    displayName: Build archives
  - task: PowerShell@2
    inputs:
      filePath: ChokuretsuTranslationBuild/build.ps1
      arguments: -nitroPacker "$(Build.SourcesDirectory)/NitroPacker/NitroPacker.exe" -haruhiCli "$(Build.SourcesDirectory)/ChokuretsuTranslationUtility/HaruhiChokuretsuCLI/bin/Debug/net6.0/HaruhiChokuretsuCLI.exe"
      workingDirectory: $(Build.SourcesDirectory)/ChokuretsuTranslationBuild
    env:
      DEVKITARM: $(Build.SourcesDirectory)/devkitPro/devkitARM
      DEVKITPRO: $(Build.SourcesDirectory)/devkitPro
    displayName: Build ROM (clean OP/ED)
  - powershell: $(Build.SourcesDirectory)\xdelta3\xdelta3.exe -e -s ChokuretsuTranslationBuild\original.nds ChokuretsuTranslationBuild\HaruhiChokuretsu.nds $(Build.ArtifactStagingDirectory)\HaruhiChokuretsu-CleanOPED-$(PatchVersion).xdelta
    displayName: Create xdelta patch (clean OP/ED)
  - task: PowerShell@2
    inputs:
      filePath: ChokuretsuTranslationBuild/copy-movies.ps1
      arguments: -assetsFolder "$(Build.SourcesDirectory)/ChokuretsuTranslationAssets" -langCode "en"
      workingDirectory: $(Build.SourcesDirectory)/ChokuretsuTranslationBuild
    displayName: Copy movies
  - task: PowerShell@2
    inputs:
      filePath: ChokuretsuTranslationBuild/build.ps1
      arguments: -nitroPacker "$(Build.SourcesDirectory)/NitroPacker/NitroPacker.exe" -haruhiCli "$(Build.SourcesDirectory)/ChokuretsuTranslationUtility/HaruhiChokuretsuCLI/bin/Debug/net6.0/HaruhiChokuretsuCLI.exe"
      workingDirectory: $(Build.SourcesDirectory)/ChokuretsuTranslationBuild
    env:
      DEVKITARM: $(Build.SourcesDirectory)/devkitPro/devkitARM
      DEVKITPRO: $(Build.SourcesDirectory)/devkitPro
    displayName: Build ROM (with movies)
  - powershell: $(Build.SourcesDirectory)\xdelta3\xdelta3.exe -e -s ChokuretsuTranslationBuild\original.nds ChokuretsuTranslationBuild\HaruhiChokuretsu.nds $(Build.ArtifactStagingDirectory)\HaruhiChokuretsu-$(PatchVersion).xdelta
    displayName: Create xdelta patch (with movies)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Nightly Patches'
      publishLocation: 'Container'
    displayName: Publish xdelta patches
  - powershell: |
      Write-Host "Uploading subbed OP/ED patch..."
      $fileToUpload = "$(Build.ArtifactStagingDirectory)\HaruhiChokuretsu-$(PatchVersion).xdelta"
      $uploadUri = "https://dockerbootstrap.blob.core.windows.net/patches/HaruhiChokuretsu-$($env:PatchVersion).xdelta?$env:WriteSAS"
      $headers = @{ 'x-ms-blob-type' = 'BlockBlob' }
      Invoke-RestMethod $uploadUri -Method PUT -Headers $headers -InFile $fileToUpload
      Write-Host "Uploading clean OP/ED patch..."
      $fileToUpload = "$(Build.ArtifactStagingDirectory)\HaruhiChokuretsu-CleanOPED-$(PatchVersion).xdelta"
      $uploadUri = "https://dockerbootstrap.blob.core.windows.net/patches/HaruhiChokuretsu-CleanOPED-$($env:PatchVersion).xdelta?$env:WriteSAS"
      $headers = @{ 'x-ms-blob-type' = 'BlockBlob' }
      Invoke-RestMethod $uploadUri -Method PUT -Headers $headers -InFile $fileToUpload
    env:
      PatchVersion: $(PatchVersion)
      WriteSAS: $(PatchesWriteSAS)
    displayName: Copy patches to Azure Storage
  - powershell: |
      Invoke-RestMethod -Uri "$env:WebHookUri" -Method POST -Headers @{ "Content-Type" = "application/json" } -Body "{`"content`": `"A new nightly patch is available!\nVersion $env:PatchVersion\nLink: https://dockerbootstrap.blob.core.windows.net/patches/HaruhiChokuretsu-$($env:PatchVersion).xdelta?$env:ReadSAS\nClean OP/ED Patch: https://dockerbootstrap.blob.core.windows.net/patches/HaruhiChokuretsu-CleanOPED-$($env:PatchVersion).xdelta?$env:ReadSAS`"}"
    env:
      WebHookUri: $(DiscordWebHook)
      PatchVersion: $(PatchVersion)
      ReadSAS: $(PatchesReadSAS)
    displayName: Post patch notification to Discord
